# Generated by Django 5.2 on 2025-06-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dashboard de Reportes', editable=False, max_length=50)),
            ],
            options={
                'verbose_name': 'Dashboard de Reportes',
                'verbose_name_plural': 'Dashboard de Reportes',
                'permissions': [('view_report_dashboard', 'Can view report dashboard')],
                'default_permissions': (),
            },
        ),
    ]
