# Generated by Django 5.2 on 2025-04-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('proveedor', 'Proveedor'), ('admin', 'Administrador')], default='cliente', max_length=20),
        ),
    ]
