# Generated by Django 5.2 on 2025-06-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('cliente', 'Cliente'), ('proveedor', 'Proveedor'), ('admin', 'Administrador')], default='usuario', max_length=20),
        ),
    ]
