# Generated by Django 5.2 on 2025-06-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        ('usuarios', '0003_alter_usuario_options_remove_usuario_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='eventos_favoritos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Sobre mí'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='tickets.evento', verbose_name='Eventos Favoritos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('cliente', 'Cliente'), ('proveedor', 'Proveedor'), ('admin', 'Administrador')], default='usuario', max_length=20),
        ),
    ]
