# Generated by Django 5.2 on 2025-06-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_usuario_actualizado_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='favoritos',
            new_name='eventos_favoritos',
        ),
    ]
