# Generated by Django 5.2 on 2025-06-13 19:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_rename_favoritos_usuario_eventos_favoritos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudproveedor',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Solicitud de Proveedor', 'verbose_name_plural': 'Solicitudes de Proveedores'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudproveedor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_proveedor', to=settings.AUTH_USER_MODEL),
        ),
    ]
