# Generated by Django 5.2 on 2025-06-14 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_solicitudproveedor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('compra', 'Confirmación de Compra'), ('evento_favorito', 'Actualización de Evento Favorito'), ('evento_aprobado', 'Evento Aprobado'), ('evento_rechazado', 'Evento Rechazado'), ('solicitud_aprobada', 'Solicitud de Proveedor Aprobada'), ('solicitud_rechazada', 'Solicitud de Proveedor Rechazada'), ('perfil_actualizado', 'Perfil Actualizado'), ('general', 'General'), ('recordatorio_evento', 'Recordatorio de Evento')], default='general', max_length=50, verbose_name='Tipo de Notificación')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace Relacionado')),
                ('read', models.BooleanField(default=False, verbose_name='Leída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
