# Generated by Django 5.2 on 2025-06-15 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudproveedor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_proveedor_recibidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
