# Generated by Django 5.2 on 2025-06-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_solicitudproveedor_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['dismissed', '-created_at'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AddField(
            model_name='notification',
            name='dismissed',
            field=models.BooleanField(default=False, verbose_name='Descartada'),
        ),
    ]
