# Generated by Django 5.2 on 2025-06-15 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_solicitudproveedor_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='dismissed',
        ),
        migrations.AlterField(
            model_name='solicitudproveedor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_proveedor_recibidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
