# Generated by Django 5.2 on 2025-06-22 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='UserNotification',
        ),
        migrations.AlterModelOptions(
            name='usernotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificación de Usuario', 'verbose_name_plural': 'Notificaciones de Usuario'},
        ),
    ]
