# Generated by Django 5.2 on 2025-06-12 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Método de Pago')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Evento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Detallada')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y Hora del Evento')),
                ('lugar', models.CharField(blank=True, max_length=250, null=True, verbose_name='Lugar del Evento')),
                ('direccion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección Completa')),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Imagen de Portada')),
                ('aprobado', models.BooleanField(default=False, help_text='Indica si el evento ha sido revisado y aprobado por un administrador.', verbose_name='Aprobado por Admin')),
                ('esta_activo', models.BooleanField(default=True, help_text='Controla si el evento está visible en el sitio (aunque esté aprobado).', verbose_name='Activo y Visible')),
                ('esta_agotado', models.BooleanField(default=False, help_text='Se marca automáticamente si no quedan boletos disponibles.', verbose_name='Boletos Agotados')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='tickets.categoria', verbose_name='Categoría')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('general', 'General'), ('vip', 'VIP'), ('preventa', 'Preventa'), ('estudiante', 'Estudiante'), ('conadis', 'CONADIS'), ('otro', 'Otro')], default='general', max_length=50, verbose_name='Tipo de Boleto')),
                ('nombre_boleto', models.CharField(blank=True, help_text="Ej: 'Entrada General Día 1', 'Mesa VIP', etc.", max_length=100, null=True, verbose_name='Nombre del Boleto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('cantidad_total', models.PositiveIntegerField(verbose_name='Cantidad Total Disponible')),
                ('cantidad_vendida', models.PositiveIntegerField(default=0, verbose_name='Cantidad Vendida')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='tickets.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'ordering': ['precio'],
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Calificación')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado de Moderación')),
                ('fecha_opinion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Opinión')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opiniones', to='tickets.evento', verbose_name='Evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opiniones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Opinión',
                'verbose_name_plural': 'Opiniones',
                'ordering': ['-fecha_opinion'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Compra')),
                ('total_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total de la Venta')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completa', 'Completa'), ('cancelada', 'Cancelada'), ('reembolsada', 'Reembolsada')], default='pendiente', max_length=20, verbose_name='Estado de la Venta')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='tickets.metodopago', verbose_name='Método de Pago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario al Momento de la Venta')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('boleto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_ventas', to='tickets.boleto', verbose_name='Boleto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tickets.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
            },
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.UniqueConstraint(fields=('nombre', 'fecha'), name='evento_unico_por_nombre_y_fecha'),
        ),
        migrations.AlterUniqueTogether(
            name='boleto',
            unique_together={('evento', 'tipo', 'nombre_boleto')},
        ),
        migrations.AlterUniqueTogether(
            name='opinion',
            unique_together={('usuario', 'evento')},
        ),
        migrations.AlterUniqueTogether(
            name='detalleventa',
            unique_together={('venta', 'boleto')},
        ),
    ]
