# Generated by Django 5.2 on 2025-06-11 23:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='tipo',
            field=models.CharField(choices=[('general', 'General'), ('vip', 'VIP'), ('preventa', 'Preventa'), ('estudiante', 'Estudiante'), ('conadis', 'CONADIS'), ('otro', 'Otro')], default='general', max_length=50, verbose_name='Tipo de Boleto'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='aprobado',
            field=models.BooleanField(default=False, help_text='Indica si el evento ha sido revisado y aprobado por un administrador.', verbose_name='Aprobado por Admin'),
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.UniqueConstraint(fields=('nombre', 'fecha'), name='evento_unico_por_nombre_y_fecha'),
        ),
    ]
