# Generated by Django 5.2 on 2025-06-09 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opiniones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='tickets.metodopago'),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tickets.venta'),
        ),
    ]
