# Generated by Django 5.2 on 2025-06-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='boleto_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
