# Generated by Django 5.2 on 2025-06-16 03:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_detalleventa_boleto_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='boleto_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
