# Generated by Django 5.2 on 2025-06-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_detalleventa_boleto_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='es_destacado',
            field=models.BooleanField(default=False, help_text='Marca este evento para que aparezca en la sección de destacados.', verbose_name='Es Destacado'),
        ),
    ]
