# Generated by Django 5.2 on 2025-06-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_evento_es_destacado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='total_venta',
        ),
        migrations.AddField(
            model_name='venta',
            name='comision_plataforma',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Comisión de la Plataforma'),
        ),
        migrations.AddField(
            model_name='venta',
            name='ganancia_proveedor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ganancia para el Proveedor'),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_bruto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Bruto de la Venta'),
        ),
    ]
