# Generated by Django 5.2 on 2025-06-22 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_venta_total_venta_venta_comision_plataforma_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('aprobacion_evento', 'Aprobación de Evento'), ('solicitud_proveedor', 'Solicitud de Proveedor'), ('comentario_pendiente', 'Comentario Pendiente'), ('error_sistema', 'Error del Sistema'), ('general', 'General Admin')], default='general', max_length=50, verbose_name='Tipo')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace Admin')),
                ('read', models.BooleanField(default=False, verbose_name='Leída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('recipient', models.ForeignKey(limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario Admin')),
            ],
            options={
                'verbose_name': 'Notificación de Admin',
                'verbose_name_plural': 'Notificaciones de Admin',
                'ordering': ['-created_at'],
            },
        ),
    ]
