# Generated by Django 5.2 on 2025-06-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_adminnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='lugar',
        ),
        migrations.AddField(
            model_name='evento',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ej: Lima, Arequipa, Bogotá', max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='evento',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada para mostrar en mapas (opcional).', max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='evento',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada para mostrar en mapas (opcional).', max_digits=9, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='evento',
            name='lugar_nombre',
            field=models.CharField(blank=True, help_text='Ej: Estadio Nacional, Centro de Convenciones', max_length=200, null=True, verbose_name='Nombre del Lugar o Recinto'),
        ),
        migrations.AddField(
            model_name='evento',
            name='pais',
            field=models.CharField(blank=True, help_text='Ej: Perú, Colombia, Argentina', max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='direccion',
            field=models.CharField(blank=True, help_text='Ej: Av. José Díaz s/n, Cercado de Lima', max_length=255, null=True, verbose_name='Dirección Completa'),
        ),
    ]
