# Generated by Django 5.2 on 2025-06-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_evento_lugar_evento_ciudad_evento_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='mapa_enlace_embed',
            field=models.URLField(blank=True, help_text='URL generada para incrustar el mapa de la ubicación del evento (iframe).', max_length=500, null=True, verbose_name='Enlace de Mapa Incrustado'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada geográfica de latitud para el mapa (ej: -12.0464).', max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada geográfica de longitud para el mapa (ej: -77.0428).', max_digits=9, null=True, verbose_name='Longitud'),
        ),
    ]
